import os
import json
import requests

SENDGRID_API_KEY = os.environ["SENDGRID_API_KEY"]

def send_email(html_body):
    # Build the SendGrid payload
    data = {
        "personalizations": [
            {
                "to": [{"email": "clayharryman@gmail.com"}],
                "subject": "ETX Job Watch Report"
            }
        ],
        "from": {"email": "clayharryman@gmail.com"},
        "content": [
            {
                "type": "text/html",
                "value": html_body
            }
        ],
        "tracking_settings": {
            "click_tracking": {
                "enable": False,
                "enable_text": False
            }
        }
    }

    # Send the email
    r = requests.post(
        "https://api.sendgrid.com/v3/mail/send",
        headers={
            "Authorization": f"Bearer {SENDGRID_API_KEY}",
            "Content-Type": "application/json"
        },
        data=json.dumps(data)
    )

    print("Status:", r.status_code)
    print("Response:", r.text)


if __name__ == "__main__":
    # Read the HTML report generated by job_watch.py
    with open("weekly_report.html", "r", encoding="utf-8") as f:
        html_body = f.read()

    send_email(html_body)
